services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    networks:
      - app-network

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    networks:
      - app-network

  jenkins:
    image: jenkins/jenkins:lts-jdk21
    container_name: jenkins-server
    user: root
    privileged: true
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network

networks:
  app-network:

volumes:
  jenkins_home:
- uses: actions/checkout@v4
- name: Build services
  run: docker compose build
